トークルーム機能の実装
sidemt/gulliver_works_message pull request #1
Opened 2021-04-25 10:33 UTC by sidemt

Generated by Coadmap

2021-04-25 10:59 UTC, sidemt commented
実装したのですが、2点気になっている点がございます。

- API仕様書では、レスポンスにAccountの profile, work_histories, academic_histories や Companyの industries を含む階層構造になっていますが、このリポジトリではこれらの関連付けが実装されていないため、 Account, Company より下の階層は含めていませんがそれで大丈夫でしょうか？下記のような形になっています。

現状のレスポンス: 
```json
{
  "rooms": [
    {
      "id": "8d8d0b63-6c15-454f-be1b-253331bb2306",
      "account": {
        "id": "ddb315e5-83cd-4c77-90ec-539dc4840884",
        "email": "test@example.com",
        "password_digest": "$2a$12$d6IQR06oSeEQ8zAe99XCVeSe6NruStRDqsx.FOrDqnvmP4FgA5V32",
        "email_verification_status": "unspecified",
        "email_verification_token": null,
        "created_at": "2021-04-25T18:12:53.639+09:00",
        "updated_at": "2021-04-25T18:12:53.639+09:00"
      },
      "company": {
        "id": "95d0c7b5-be5c-4b79-b601-e9427caaf34c",
        "name": "株式会社SIMULA Labs",
        "name_kana": "シミュララボ ",
        "head_office_location": "東京都港区元赤坂1-7-18",
        "year_of_establishment": "2015",
        "hp_url": "https://simula-labs.com/",
        "phone": "03-1234-5678",
        "capital": 1520,
        "is_listed": false,
        "representative": "牧野暉弘",
        "representative_kana": "まきのあきひろ",
        "net_sales": "5000",
        "numbers_of_employees": "20",
        "average_age": 28,
        "business_summary": "事業概要",
        "corporate_pr": "ヒトが生涯の中で最も長く過ごす「働く」という時間。 日本の場合、この働く時間をどう過ごすかはほとんど就活の間に決まってしまっていると言ってもいいでしょう。"
      }
    }
  ]
}
```

API仕様書のRoomモデル:
![api_spec_room](https://user-images.githubusercontent.com/25644062/115990578-fd9af800-a5fe-11eb-9740-c645d85c6b79.png)


- 同一アカウント-会社間で1件に制限するバリデーションを追加したのですが、このバリデーションエラーが発生するようなリクエストを投げると、 `uninitialized constant ExceptionHandler::Raven` エラーが発生し、HTTPステータス500のエラーが返ってきてしまいます。これはどうしたらいいでしょうか…。

![uninitialized_constant_raven](https://user-images.githubusercontent.com/25644062/115990803-41423180-a600-11eb-983c-5d3ba155a6dd.png)

テスト結果はこちらです。よろしくお願いいたします。
※バリデーションのテストはModelのテストに追加し、Controllerのテストには含めていません。

![9416_test_results](https://user-images.githubusercontent.com/25644062/115990860-8a928100-a600-11eb-9ae6-f2c4ed59716d.png)

2021-04-26 11:11 UTC, uchidataku requested changes
1. OpenAPIに定義してあるレスポンスは無視していただいて大丈夫です
もし実装される際に前回のリポジトリを引き継いで実装した場合はAcademicHistoryなども返ってくる形になると思いますが、引き継いでいない場合は気にしなくて大丈夫です
OpenAPIの仕様上、繋がって表示されてしまうのはしょうがないって感じですね。。

2. 大変失礼しました。
このRavenはSentry用のものなので、ExceptionHandlerから`Raven.capture_exception(e)`を全て削除してもらって大丈夫です
そもそもボイラープレートに残っているのが正しくなかったので修正しておきます。
ありがとうございます。

2021-04-26 11:11 UTC, uchidataku commented on app/controllers/v1/rooms_controller.rb
> +    load_and_authorize_resource only: :show
shallowを使ってシンプルに書けると思います

2021-04-26 11:11 UTC, uchidataku commented on app/models/account.rb
> +  has_many :rooms, dependent: :destroy
例えば求職者側のアカウントが削除されても企業側の方でトーク履歴が残っていた方が好ましいので、nullifyの方が良いですね

2021-04-26 11:11 UTC, uchidataku commented on app/models/company.rb
> +  has_many :rooms, dependent: :destroy
同様ですね

2021-04-26 11:11 UTC, uchidataku commented on config/routes.rb
> +    resources :rooms, only: :show
これを書かずにshallowでいけますね

2021-04-26 11:11 UTC, uchidataku commented on config/routes.rb
> +      resources :rooms, only: :show
同様です

2021-04-26 11:11 UTC, uchidataku commented on db/migrate/20210421152412_create_rooms.rb
> +    end
Modelの方でユニーク制約をかける場合、基本的にはDBにもかけましょう
細かい話は置いておきますが、アプリケーションロジックとデータベースロジックが違うと不整合が起きてしまう可能性があり、好ましくないです

2021-04-26 11:11 UTC, uchidataku commented on app/controllers/enterprise/v1/rooms_controller.rb
> +      load_and_authorize_resource only: :show
shallowを使ってシンプルに書けると思います

2021-05-09 12:08 UTC, sidemt commented on db/migrate/20210421152412_create_rooms.rb
> +    end
ご指摘ありがとうございます！
こちら、新たにmigrationファイルを追加して対応しました。

2021-05-09 12:10 UTC, sidemt commented
@uchidataku 期間が空いてしまってすみません。
ご指摘いただいた点、修正してpushしました。お手数ですが再度レビューをよろしくお願いいたします！

テスト結果は下記の通りです。

![image](https://user-images.githubusercontent.com/25644062/117571774-e4b83980-b10a-11eb-9feb-8ee8a72133f9.png)

2021-05-10 05:51 UTC, uchidataku approved these changes
良いですね！
LGTMです！

2021-05-10 07:12 UTC, merged